##Numpy - Numerical Python

Advantages:
1. Mathematical Operations
2. Faster than lists

In [2]:
import numpy as np
from time import process_time

In [3]:
#Time taken by a list
start_time = 0
lst = [i for i in range(10000)]
lst = [i+5 for i in lst]
end_time = process_time()
print(end_time - start_time)

2.15625


In [5]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5  

end_time = process_time()

print(end_time - start_time)

0.0


In [7]:
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [10]:
np_array = np.array([1,2,4,54,6])
print(np_array)
type(np_array)

[ 1  2  4 54  6]


numpy.ndarray

In [11]:
np_array.shape

(5,)

In [12]:
# create a numpy array of Zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [13]:
# create a numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [14]:
# array of a particular value
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [15]:
# create an identity matrix
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [16]:
# create a numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.35498142 0.15957759 0.52615811 0.64907326]
 [0.11501132 0.34431417 0.96521766 0.41775097]
 [0.74591293 0.39528805 0.32859705 0.16650489]]


In [17]:
# random integer values array within a specific range
c = np.random.randint(10,100,(3,5))
print(c)


[[55 41 45 57 45]
 [34 43 43 25 35]
 [77 88 79 71 80]]


In [18]:
# array of evenly spaced values --> specifying the number of values required
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [19]:
# array of evenly spaced values --> specifying the step
e = np.arange(10,30,5)
print(e)


[10 15 20 25]


In [20]:
# convert a list to a numpy array
list2 = [10,20,20,20,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray